### ISSUE TITLE
Resolving parameter destination

### ISSUE THREAD

**Issue by garethr** [deislabs/cnab-spec#100]
https://github.com/deislabs/cnab-spec/pull/87 was merged last week.  

@technosophos @bacongobbler @radu-matei this is unfortunately a mistake I think and wants reverting. The spec describes the case for destination not being set in `bundle.json`, a default ENV value with a default name of `$CNAB_P_<NAME>`:

https://github.com/deislabs/cnab-spec/blob/master/101-bundle-json.md#resolving-destinations

With the change in #87 the spec is currently inconsistent between the description of the `destination` field and the resolution details and examples. Personally, I much prefer the original approach, it's less verbose for end users.

**Comment by technosophos** [comment]
You are right. My mistake. I'll get it fixed.

**Comment by vdice** [comment]
+1 on the original approach.  Got around to revisiting the example bundles in https://github.com/deislabs/example-bundles to get CI/validation back on track/passing and one hurdle, besides https://github.com/deislabs/example-bundles/issues/80, is this change.

Therefore, if/once this is fixed and `destination` is no longer required, no updates across the example bundles will be needed, for this particular detail.

**Comment by vdice** [comment]
Closing now that #105 has been merged.
