### ISSUE TITLE
Removing support for CNAB_P_<param>

### ISSUE THREAD

**Issue by technosophos** [deislabs/cnab-spec#105]
Should we remove support for `CNAB_P_<param name>`?

Early CNAB did not allow custom parameter paths or env vars, and instead automatically injected parameters according the the formula `CNAB_P_<PARAM NAMe>` (e.g. `CNAB_P_PORT`)

Later, we added support for `destination`, which allows setting the desired destination.

Is it time to remove the `CNAB_P_` style parameters, or should we leave them?

**Comment by glyn** [comment]
I vote to remove them.

**Comment by vdice** [comment]
Related: https://github.com/deislabs/cnab-spec/issues/100

If support is removed, will `destination` remain a _required_ field (and must be accompanied either by an `env` or a `path` entry?) (per https://github.com/deislabs/cnab-spec/blob/master/101-bundle-json.md#parameters)

(No vote preference for me, just wanted to get clarity on the question above.)

**Comment by technosophos** [comment]
Yup. @garethr -- as owner of that issue (and CNAB Python maintainer), do you have any preferences on this?

**Comment by technosophos** [comment]
I wrote a PR to remove this at #110.

**Comment by garethr** [comment]
While I think the magic is useful, I'm more in favour of a smaller spec. So I'm +1 on removing and making destination required. My concern with #100 was the inconsistency. +1 on #110

**Comment by technosophos** [comment]
Okay. I'll update that PR (with the recent suggestions) and merge that. I feel better about eliminating magic variables.

**Comment by vdice** [comment]
On that note, PR to update example-bundles in: https://github.com/deislabs/example-bundles/pull/88
