### ISSUE TITLE
Address redundancy in spec regarding declarative image references and runtime references

### ISSUE THREAD

**Issue by jeremyrickard** [deislabs/cnab-spec#113]
See https://github.com/deislabs/cnab-spec/blob/master/101-bundle-json.md#the-image-map. Refs and image map injection at runtime are redundant  and we should clarify the specification to remove the redundancy. 

@simonferquel @lachie83 @technosophos

**Comment by technosophos** [comment]
I am taking a shot at fixing this, and will open a PR.
