### ISSUE TITLE
Credential requirement and optional deployments

### ISSUE THREAD

**Issue by ryanmoran** [deislabs/cnab-spec#119]
The specification makes an effort to separate credentials from parameters with the intention outlined [here](https://github.com/deislabs/cnab-spec/blob/master/101-bundle-json.md#credentials).

It defines each as follows:
> A parameter represents application configuration.
> A credential represents the identity of the agent performing the action.

The other condition that differentiates credentials from parameters is their "required-ness". Parameters, if provided a `defaultValue`, are not required, while credentials are required in all cases.

Given this context, I am wondering how we might be able to support a bundle with the following needs:
1. The bundle is for a database like MySQL.
2. The bundle has 2 modes of operation: standalone or service broker.
    * In the standalone case, the database acts as a dedicated single-tenant database.
    * In the service broker case, the bundle includes a service broker deployed in addition to the database to handle [OSBAPI](https://www.openservicebrokerapi.org/) requests and support multi-tenancy.
3. Bundle users can choose which mode of operation they want to install.
4. When choosing the broker option, the service broker is installed on to a platform that is distinct from the database (maybe the database is stood up as a VM on Azure, and the broker is deployed as a Pod on Kubernetes).

Given the constraints above (mostly the one where depending upon the option chosen by the bundle user, the agent will have a different set of identities and thus different credential requirements), how do we see CNAB supporting this type of optional deployment process?

**Comment by technosophos** [comment]
We could add a `required` flag to credentials. I mean, that does seem like a legitimate thing to do.
