### ISSUE TITLE
Support image relocation by the invocation image

### ISSUE THREAD

**Issue by glyn** [deislabs/cnab-spec#122]
This issue follows on from an earlier [discussion](https://github.com/deislabs/cnab-spec/pull/117#discussion_r262118413) in PR 117 and a [comment](https://github.com/deislabs/duffle/issues/217#issuecomment-468145253) in duffle issue 217.

Moving images to a private registry is what we in the [riff project](https://projectriff.io/) call _image relocation_. For background, please see the design document [Private Docker Registries and riff](https://docs.google.com/document/d/1Y0wKbZWhOe2GlbZzksceKjxJhI1wxsgM8_IDCoq5gvs/edit?usp=sharing), the [riff issues labelled with `private-registry`](https://github.com/projectriff/riff/issues?q=label%3Aprivate-registry+is%3Aclosed), and the corresponding PRs. [This information refers to open source versions of `riff-distro` and `riff image` commands, but these have been moved to closed source. See the [PFS documentation](https://docs.pivotal.io/pfs/install-relocate-images.html) for usage information.]

In this issue, we propose that image relocation should be the responsibility of an invocation image (the relocation logic probably packaged in a base invocation image which could be augmented with tooling). A parameter would specify the target registry and the invocation image would be responsible for tagging and pushing images to the target registry and rewriting kubernetes configuration files in the bundle to refer to the relocated image names. This approach puts the least burden on the CNAB spec and CNAB runtimes.

Image relocation could apply to thick bundles (probably most suited to an air gapped installation) or thin bundles (where the user has a network zone with read access to the internet and read-write access to the target registry). For thick bundles, the invocation image doing relocation would need access to the binary images in the bundle. This is the subject of https://github.com/deislabs/cnab-spec/issues/95.

The remaining consideration is which action should be responsible for image relocation. As pointed out in https://github.com/deislabs/cnab-spec/issues/95#issuecomment-467517844 and following, it might make sense to separate out a custom action to push images to a private registry as it would probably not be desirable to repeat pushing images when installing the same bundle in multiple host environments sharing a private registry. However, since there is no state carried between actions, the parameter(s) enabling relocation would need to be passed to the `install` action so it could rewrite any references to the original images. Assuming the image push logic is idempotent and efficient, it may be simplest to make relocation part of the `install` action and avoid using a custom action.

An older version of the CNAB spec described an [image map](https://github.com/deislabs/cnab-spec/blob/5943e6da6cb17efc057bc520cf4708142af2bc01/101-bundle-json.md#the-image-map) which contained `refs` that listed the places in a bundle's files which referred to each image. This could make rewriting references to the original images more robust. However, this could be achieved by passing custom metadata in a [custom extension](https://github.com/deislabs/cnab-spec/blob/master/101-bundle-json.md#custom-extensions).

No other changes (other than https://github.com/deislabs/cnab-spec/issues/95) to the CNAB spec or CNAB runtimes are necessary.

**Comment by glyn** [comment]
There is a "chicken and egg" problem with this approach: what does it mean for an invocation image to relocate itself? By the time an invocation image is running, it's too late to relocate itself. Closing.

**Comment by technosophos** [comment]
This is why I had suggested an `import` action. An image needn't be relocated before it can be executed (there is generally no prerequisite that it be pulled from a repo). So if we added an `import` action, you could run something like `duffle import foo.cnab --set registry=matt.azurecr.io/myproject` and have it do just the import step. There is no reason why an invocation image cannot mount its own layer diagram, too.

So it could work... but it's a little weird.
