### ISSUE TITLE
Image map needs to include original image names

### ISSUE THREAD

**Issue by glyn** [deislabs/cnab-spec#134]
In order for invocation images to patch any references to images, the CNAB's [image map](https://github.com/deislabs/cnab-spec/blob/master/101-bundle-json.md#the-image-map) needs to include the original image names as well as the (current/relocated) image names, for example:
```
{
"images": {
        "frontend": { 
            "description": "frontend component image",
            "imageType": "docker",
            "originalImage": "docker.io/auser/vote-frontend:a5ff67...",
            "image": "gabrtv.azurecr.io/gabrtv/vote-frontend:a5ff67...",
            "digest": "sha256:aca460afa270d4c527981ef9ca4989346c56cf9b20217dcea37df1ece8120685"
        },
        "backend": {
            "description": "backend component image",
            "imageType": "docker",
            "originalImage": "docker.io/auser/vote-backend:a5ff67...",
            "image": "gabrtv.azurecr.io/gabrtv/vote-backend:a5ff67...",
            "digest": "sha256:aca460afa270d4c527981ef9ca4989346c56cf9b20217dcea37df1ece8120685"
        }
    }
}
```

It may be desirable to avoid repeating the image name when images have not been relocated. One way to do this would be to omit the original image name, the implication being that the original image name is the same as the (current) image name.

**Comment by technosophos** [comment]
@simonferquel How do you all handle this situation?

**Comment by simonferquel** [comment]
For now we put the original image name in the description field. That is not ideal.
Also, our invocation images don't use the original name at all, but that would be nice to be able to put that in some kind of service label so that `docker app status` could print indications saying that the original image reference for a given service was `mysql:latest` instead of just printing the relocated digest-qualified image ref

**Comment by technosophos** [comment]
Could we call it `defaultImage` instead of `originalImage`?

**Comment by simonferquel** [comment]
I prefer `originalImage` because `defaultÌmage` implies "it should be the image ref you should use if you don't really understand clearly image relocation mechanism" (where `originalImage` conveys the notion of "at build time, this was the image name value, but use `image` at runtime as it can be overriden).

**Comment by technosophos** [comment]
That is a good point. Do we envision cases where "image" and "originalImage" would be the same?

**Comment by glyn** [comment]
> That is a good point. Do we envision cases where "image" and "originalImage" would be the same?

If image relocation wasn't necessary, then these fields could logically be the same. In PR 137, I've proposed that "originalImage" should be OPTIONAL and have default value the same as that of "image".

**Comment by simonferquel** [comment]
Aggreed with @glyn

**Comment by technosophos** [comment]
There are two ways to intepret "OPTIONAL" in this case:

1. It is optional for the CNAB runtime to support `originalImage` at all
2. It is optional, in a specific case, for the runtime to provide an `originalImage` value

I'm assuming that 2 is what you mean. In this case, the absence of `originalImage` indicates that...?

- The `image` has not been changed
- For whatever reason, the `originalImage` reference has not been included

And this gets us to the salient point: If `originalImage` is not specified, what is the desired behavior? Does the bundle try to replace images by name, as Docker App does now, or does it assume that there is no substitution to be made?

**Comment by glyn** [comment]
> There are two ways to inte[r]pret "OPTIONAL" in this case:
> 
> 1. It is optional for the CNAB runtime to support `originalImage` at all
> 2. It is optional, in a specific case, for the runtime to provide an `originalImage` value
> 
> I'm assuming that 2 is what you mean. In this case, the absence of `originalImage` indicates that...?

Correct. I hope this is clear in PR 137: `originalImage` is defined in `bundle.schema.json`.

> 
> * The `image` has not been changed
> * For whatever reason, the `originalImage` reference has not been included
> 
> And this gets us to the salient point: If `originalImage` is not specified, what is the desired behavior? Does the bundle try to replace images by name, as Docker App does now, or does it assume that there is no substitution to be made?

I've updated PR 137 to clarify this case: the run tool MAY replace images by name, as Docker App does now.
