### ISSUE TITLE
images and invocationImages should be consistent

### ISSUE THREAD

**Issue by sbawaska** [deislabs/cnab-spec#138]
Currently, the spec defines `images` as a map whereas `invocationImages` is an array. I think these two sections should be consistent so as not to create a gotcha for bundle authors.

**Comment by silvin-lubecki** [comment]
The PR introducing the map is [here](https://github.com/deislabs/duffle/pull/605).
As far as I can remember we changed the type to a map only because it was simpler to serialize as is  and to inject it in the invocation image.
That said, you are totally right we introduced an inconsistency here.
I honestly don't have a strong opinion if we should move back to an array and add a new field, or if we should move the `images` to a map, but we definitely need to do something 👍

**Comment by silvin-lubecki** [comment]
cc @simonferquel

**Comment by simonferquel** [comment]
The main reason for this difference, is that an `invocation image` is an attribute of the bundle itself (which can have multiple values, to support different runtime drivers), while an `image` is an attribute of a component deployed by the bundle. Thus `invocationImages` is a multi-valued attribute of the bundle (a simple flat list), while `images` is a map associating a component name with its related image.

**Comment by radu-matei** [comment]
This is also relevant in how the tooling is going to use / select the correct invocation image:

- the image type (VM / container)
- architecture (ARM / x86)

If we go forward with a map for the invocation image, it would be ideal if the key of the map is relevant in helping the tooling select the appropriate one.

**Comment by sbawaska** [comment]
If we are implying a relationship between invocationImage and image (from the above two comments), would it then make sense to embed images within invocationImages?

This will also help alleviate the initial confusion when someone new looks at the spec: (example of initial confusion on tgik: https://youtu.be/R_Wul_xdHsk?t=2157. However, that was quickly resolved later)

**Comment by radu-matei** [comment]
I'm not sure I follow the implied relationship between the two -- images are part of the application, while the invocation images define how the bundle is going to be deployed, and I think we should keep the distinction between the two.

**Comment by technosophos** [comment]
I believe this issue can now be closed. Feel free to re-open if there are additional actionable items.
