### ISSUE TITLE
Thick bundle: clarify how invocation images are "air-gapped-aware"

### ISSUE THREAD

**Issue by simonferquel** [deislabs/cnab-spec#142]
As commented here: https://github.com/deislabs/cnab-spec/pull/139#discussion_r266346110, having thick bundle only fix the "distribution" aspect of the air-gapped scenarios, but for an invocation-image to leverage the thick bundle content (and know that it must use it), we are missing runtime support. Thus I am not sure if thick-bundle should make it in the v1 of the spec, or if we should release a v1 without, and use some time to think about runtime support.

I like to use a practical example for that, so, we can try to elaborate solution with using a "docker-compose" CNAB example:
- this bundle has 1 image defined for each service
- it handles the injected image map to work well with image relocation
- however, its logic is to create Docker containers referencing the images present in the image map, knowing nothing about "air-gapped" environment and how to load image data.

So we need:
- a common way to indicate we are running from a think-bundle and thus should use a "air-gapped" logic within the invocation image
- a way to expose component images to the invocation image (the docker-compose invocation image could use `docker load` or some random image provisioning API).

I guess there will be also limitations on some bundles though. For example the Kubernetes API does not provide anything to provision images at the cluster level, and thus I can't see a way to have a CNAB deploying workloads on K8s to play in those scenarios.

**Comment by radu-matei** [comment]
Regarding the air-gapped scenario with Kubernetes -- my assumption (it needs validation, though) is that these types of clusters usually have a local private registry that they use -- so when importing a thick bundle, we could point the run tool to the container registry and hydrate it before executing any CNAB action.

**Comment by GreenCee** [comment]
Just realized the issue I opened was much closer related to this, so closing that duplicate and placing the issue in here:


In stepping through thin/thick bundle workflows we've identified a path forward that preserves the requirement of airgap 'thick bundle' installs without requiring entirely separate codepaths. The result is that the runtime and the invocationImages can be created in such a way they can be naïve of where the bundle is being installed as well as adding the ability for 'manual' relocation for non-supported images (Obscure VM types, purposely for separation of duties between pushing an image and pulling an image).
A lot of this ties back to Duffle's initial concept of rewrite
Relocation as a concept is the act of renaming and/or moving an image while preserving the relevant digests and relationships. In the most common case this will be OCI moves between registries. Another way would be registering a VM or Function at a different location (AKA my AWS account's AMI gallery)
Taking a simple example of a CNAB that installed a helm chart, the invocationImage would be required to pattern match and update references to these called out images within the helm chart.
For the Spec we should remain agnostic on the how, whether a find/replace, or just using the updated "image:" value if it just tacks on that value to a command internally. Everything will have a slightly different way of accomplishing this, but beleive tooling will emerge to take an aribitrary Helm chart or Docker Componse file and pull out image references that will be relocated and the rewrite logic.
@jeremyrickard @carolynvs - I'm curious if this would provide the right things needed for Porter to 'thick enable' an aribitrary Helm Chart, or Kubernetes Deployment. For example the burden of logic would be one-time at the mix-in level
This should result in a Spec PR that requires an invocationImage(or bundle?) to declare it supports relocation aka Thick Bundle
Assumptions to poke holes in logic
InvocationImages will have access to the bundle.json (#144)
The bundle.json will contain the replaced or relocated either embedded in parameters or a similar node (IssueTBD) with 'originalImage' and 'image' available
Runtimes should be able to optionally support thick bundles. Should we echo this in the bundle/InvocationImage requirements to be compliant?
The outcome of relocation (deislabs/duffle#671) will influence this as well.

**Comment by GreenCee** [comment]
This tool came up at RH Summit: https://github.com/RedHatOfficial/odie/blob/master/README.adoc
In this case ODIE aims to provide a 100% batteries included environment to the point of being a bootable DVD.


I don't think CNAB is aiming to be a bootstrap-from-zero solution.
It may contain infrastructure-like things, but typically an environment will have services to integrate with through relocations, parameters and supplemental tooling.

Maybe aim this for the next meeting to come to consensus and land on CNAB's sweet spot in infrastructure bootstrap vs. runtime requirements for application bootstrap

**Comment by glyn** [comment]
I don't think invocation images need to be "air-gapped-aware" _per se_: they just need to support relocation mappings.

**Comment by glyn** [comment]
Consensus at CNAB meeting: this isn't a problem. Closing.
