### ISSUE TITLE
Expose custom extensions to invocation images

### ISSUE THREAD

**Issue by glyn** [deislabs/cnab-spec#143]
Invocation images, and particularly base invocation images, need to access [custom extensions](https://github.com/deislabs/cnab-spec/blob/master/101-bundle-json.md#custom-extensions) so that (base) invocation image specific data can be usefully stored in a CNAB.

A use case is where a base invocation image would like to use a custom extension that specifies where image names occur in kubernetes configuration YAML files in the bundle. Tooling could produce such a custom extension that would list a set of path expressions for each reference. This would assist the base image in patching the YAML files, e.g. when image relocation has occurred and the original image names need replacing, without doing a (risky) global change.

At runtime the custom extensions section of the CNAB is mounted in file `/cnab/app/custom-extensions.json`.

**Comment by technosophos** [comment]
Ah! You beat me to it! I was thinking in #144 that we should just add back the requirement that the entire `bundle.json` be mounted at a known location in the invocation image. Thoughts on that?

**Comment by glyn** [comment]
> Ah! You beat me to it! I was thinking in #144 that we should just add back the requirement that the entire `bundle.json` be mounted at a known location in the invocation image. Thoughts on that?

I prefer the solution in #144 to the one above. Let's keep this issue open until #144 is implemented.

**Comment by technosophos** [comment]
Closed, since #144 was closed
