### ISSUE TITLE
Mount entire `bundle.json` as a file at `/var/run/cnab/bundle.json`

### ISSUE THREAD

**Issue by technosophos** [deislabs/cnab-spec#144]
In the first few drafts of the CNAB spec, the `bundle.json` was accessible inside of the invocation image (as part of the building process, it was copied in). We removed that when we lowered the requirements for building a bundle.

Now, there are several different pieces of the `bundle.json` that are interesting to authors of invocation images. Should we just require that the `bundle.json` be mounted at a fixed location (`/var/run/cnab/bundle.json`, for example)?

**Comment by glyn** [comment]
Yes, I think this is a great idea. I can't see any downside. In particular, this approach would solve https://github.com/deislabs/cnab-spec/issues/143 by allowing invocation images to see custom extensions. It would also simplify the runtime by avoiding it having to treat several pieces of `bundle.json` similarly.

**Comment by simonferquel** [comment]
Agreed!

**Comment by simonferquel** [comment]
cc @silvin-lubecki, we need to track this for docker-app (it will change the way we need to extract the image map in the run tool).

**Comment by glyn** [comment]
@youreddy You are working on a PR to fix this issue, so I took the liberty of assigning this issue to you. Please unassign if that's not appropriate.

**Comment by jeremyrickard** [comment]
Closed by #196
