### ISSUE TITLE
Support relocation of invocation images

### ISSUE THREAD

**Issue by glyn** [deislabs/cnab-spec#157]
In some scenarios, such as deploying a thick bundle in an air-gapped system, the runtime needs to relocate invocation images (as well as the other images referenced by the bundle). To support this, the optional `originalImage` and `originalDigest` fields should be added to invocation images.

**Comment by simonferquel** [comment]
same as for images, the digest should not change because of relocation. If it does, it means that the content of the image itself has changed

**Comment by glyn** [comment]
> same as for images, the digest should not change because of relocation. If it does, it means that the content of the image itself has changed

I agree with the sentiment, but please note that if the digest changes because a registry-specific compression algorithm was used, then it is conceivable for the uncompressed image content not to have changed even though the digest has.

The image relocation code preserves digests by carefully copying blobs between registries without changing their compression.
