### ISSUE TITLE
rename digest field to contentDigest

### ISSUE THREAD

**Issue by michelleN** [deislabs/cnab-spec#159]

**Comment by jeremyrickard** [comment]
As part of this, should we spell out more about how to calculate the content-digest and specify that it isn't whatever the registry digest is? I think we should make it a little more clear so we don't end up with runtimes calculating things differently that would make things go sideways if people try to move bundles between runtimes.

**Comment by technosophos** [comment]
We're trying to get everything consistent, so it should be `contentDigest`, not `content-digest`. See #149 .

**Comment by simonferquel** [comment]
Just edited the title based on @technosophos remark
