### ISSUE TITLE
Proposal:Add an immutable property to bundle parameter object

### ISSUE THREAD

**Issue by simongdavies** [deislabs/cnab-spec#181]
Some parameters to bundles may be immutable, examples include:

- properties of resources that can only be set when those resources are created (e.g. in Azure a VM password can only be set when a VM is created, attempts to update it will be met with failure)

- where a bundle targets new or existing infrastructure resources its important to know on subsequent actions if those infrastructure resources were created as part of the application install (e.g. if I create a resource as part of an bundle install then I need to know on uninstall in order to handle the cleanup correctly) 

Proposal is to add a property **immutable** to the parameter object with a default setting of  false, immutable properties would only be able to be set on the install action,

**Comment by simonferquel** [comment]
I agree with this, should we consider that for 1.0.0 ?

**Comment by radu-matei** [comment]
I can't think of reason not to have this.

**Comment by technosophos** [comment]
I started to implement this, but it seems that I can accomplish the desired behavior by just specifying `"applyTo": ["install"]`, which effectively masks the parameter for anything but install operations.

Is there something more we need?

**Comment by simongdavies** [comment]
if we used applyto doesn't that mean by definition that the value would not get presented to other actions? I need to be able to read the value in all actions but only set it at install time , I _think_ that is the difference?
