### ISSUE TITLE
Remove tar file representation of images in thick bundles

### ISSUE THREAD

**Issue by glyn** [deislabs/cnab-spec#182]
The consensus at the 29 May CNAB community meeting was that we remove the multiple tar file representation of images in thick bundles from the spec and focus on the OCI image layout representation.

**Comment by simonferquel** [comment]
Agreed, should be done for 1.0.0

**Comment by radu-matei** [comment]
LGTM.

**Comment by technosophos** [comment]
All we need is a PR for this, I think. Nobody seems to disagree.
