### ISSUE TITLE
Proposal: Require output paths to be subpaths of /cnab/app/outputs

### ISSUE THREAD

**Issue by jlegrone** [deislabs/cnab-spec#184]
Right now the spec does not specify a location for [output paths](https://github.com/deislabs/cnab-spec/blob/0abbb9e0d52b0ae631d12cf8278711c69fb24c64/101-bundle-json.md#outputs). This can make driver implementation tricky in some cases, and can also lead to conflicts with params and credentials.

I propose modifying the spec to say the following:

1. An output path MUST be a subpath of `/cnab/app/outputs`
2. Param or credential paths MUST NOT be subpaths of `/cnab/app/outputs`

**Comment by technosophos** [comment]
This makes sense to me. In fact, I can't think of any reason not to do this. @jeremyrickard ?

**Comment by jeremyrickard** [comment]
Nope, this sounds good to me.
