### ISSUE TITLE
Consider removing "platform" field in image and invocationImage

### ISSUE THREAD

**Issue by simonferquel** [deislabs/cnab-spec#185]
The image reference can point to either a single or multi-arch image in the registry. I think having the platform spec in bundle.json as well is confusing.

This remark might be nuanced for VM based scenarios, wdyt ?

**Comment by technosophos** [comment]
1. We need to keep it for VM and MSIX
2. I am told that not all registries correctly do multi-arch, so we need to leave it for those cases. However, I don't know what registries those are.

**Comment by technosophos** [comment]
In #179, I suggested replacing `platform` with `labels` and making it free-form name/value pairs. This actually comes closer to meeting the original design objectives of that section, which was to allow a user to pick invocation image variants.
