### ISSUE TITLE
Proposal: Remove vague credential text

### ISSUE THREAD

**Issue by jeremyrickard** [deislabs/cnab-spec#198]
In the [credentials](https://github.com/deislabs/cnab-spec/blob/master/101-bundle-json.md#credentials) section of the [101-bundle-json.md](https://github.com/deislabs/cnab-spec/blob/master/101-bundle-json.md), there is text about the use of `path` and `env`: 

> When both a path and an env are specified, only one is REQUIRED (properties are disjunctive). To require two presentations of the same material, two separate entries MUST be made.

The intent of this text is unclear and confusing. 

* Does it imply that one should _*NOT*_ specify both? If so we should error
* Does it imply that a runtime can populate only one and you should therefore specify it twice?

I think both of these are undesirable and we should remove this text and specify that a runtime should populate both if both are provided.

**Comment by technosophos** [comment]
I was looking at this last week.

The text as it stands now states that if a configuration is supplied with two targets, the runtime only needs to populate one destination.

But digging back through this history, it appears that that particular line was referring to the way credentials were searched for on the user's machine (prior to credential sets). So I think this can be safely removed. The appropriate text would indicate that when both a path and an env var exist, both MUST be populated.

**Comment by jeremyrickard** [comment]
That fits with what we have for parameters.

**Comment by jeremyrickard** [comment]
Closed by #199
