### ISSUE TITLE
Including the bundle.json in the invocation image creates a loop

### ISSUE THREAD

**Issue by astrieanna** [deislabs/cnab-spec#201]
Currently, the [file system layout for invocation images](https://github.com/deislabs/cnab-spec/blob/master/102-invocation-image.md#the-file-system-layout) shows the bundle.json file includes in the image.

This creates a loop:
* bundle.json includes a checksum for the invocation image
* the invocation image includes bundle.json, changing its checksum
* bundle.json changes due to the checksum changing
* etc...

Two possible paths that resolve the loop are:
1) Defining the invocation image bundle.json to be different from all other bundle.json files in that the checksum doesn't matter (or doesn't exist) for the invocation image. This is easy, but is likely to cause bugs for some CNAB authors later when the bundle.json they pass to a runtime does not exactly match the bundle.json baked into their invocation image.

2) Having CNAB runtimes make the bundle.json available to the invocation image at a well-known path. The runtime has bundle.json (the source of truth) and already makes inputs available to the invocation image via file paths (parameters, credentials).

The PR that introduced the change, and the issues that motivated it:
https://github.com/deislabs/cnab-spec/pull/196
https://github.com/deislabs/cnab-spec/issues/144
https://github.com/deislabs/cnab-spec/issues/195

**Comment by ryanmoran** [comment]
I believe that the inclusion of the bundle.json file in that part of the spec is a mistake. The bundle.json is not baked into the invocation image, but injected into the container that invokes the run tool at run time as explained [here](https://github.com/deislabs/cnab-spec/blob/master/103-bundle-runtime.md#bundle-definition).

I propose that we remove the mention of the bundle.json file from the [file system layout for invocation images section](https://github.com/deislabs/cnab-spec/blob/master/102-invocation-image.md#the-file-system-layout).
