### ISSUE TITLE
103-bundle-runtime: is defaulting the main entry point a MUST or a SHOULD?

### ISSUE THREAD

**Issue by astrieanna** [deislabs/cnab-spec#207]
In [103-bundle-runtime: The Run Tool](https://github.com/deislabs/cnab-spec/blob/master/103-bundle-runtime.md#the-run-tool-main-entry-point), the first paragraph of the section includes the following:
> In addition, images used as invocation images SHOULD also default to running /cnab/app/run. For example, a Dockerfile's exec array MUST point to this entry point.

This seems contradictory. If Dockerfile's exec array is an example of the previous sentence, then the all-caps words should match. From the surrounding context, it seems like the `MUST` should become a `SHOULD`?

**Comment by technosophos** [comment]
SHOULD is the correct term here. I'll do a quick PR.
