### ISSUE TITLE
Can a credential be a directory?

### ISSUE THREAD

**Issue by jeremyrickard** [deislabs/cnab-spec#214]
Per https://github.com/deislabs/duffle/issues/791, can credentials represent a directory?

```
The credentials container is a map of human-friendly credential names to a description of where the invocation image expects to find them.
The name key MUST be human-readable
path describes the absolute path within the invocation image where the invocation image expects to find the credential. Specified path MUST NOT be a subpath of /cnab/app/outputs.
env contains the name of an environment variable that the invocation image expects to have available when executing the CNAB run tool (covered in the next section).
description contains a user-friendly description of the credential.
required indicates whether this credential MUST be supplied. By default, it is false, which means the credential is optional. When true, a runtime MUST fail if the credential is not provided.
```

Which is clarified by:

```
If path is set, the value of the credential MUST be written into a file at the specified location on the invocation image's filesystem. This file name MUST NOT be present already on the invocation image's filesystem.
```

Should "file" here be jsut a file? Or can it also be a directory?

**Comment by technosophos** [comment]
I guess we could do directories... but it is more of a security risk. I mean, stupid example is, I have an SSH key in `~/.ssh` that I want to load up. At the time, I have only one key in there, so I set up my initial credential set to use that directory. Later, I add more keys. Then I run an upgrade using the same credential set. Now I have inadvertently exposed all of my SSH keys.

**Comment by jeremyrickard** [comment]
I think that’s a good reason why not to do a directory. The explicitness of single file/env variables has a better audit ability I think.

**Comment by jeremyrickard** [comment]
Closing based on the discussion above.
