### ISSUE TITLE
Make specifying required parameters consistent with required credentials

### ISSUE THREAD

**Issue by jlegrone** [deislabs/cnab-spec#222]
Specifying required credentials is currently done via a boolean `required` property on each credential:

https://github.com/deislabs/cnab-spec/blob/8ec6c23db9bbc404be551ef13872c19fe03cc437/schema/bundle.schema.json#L22-L26

While required parameters are currently listed in a `required` array of strings referencing parameter keys:

```json
{
  "parameters": {
    "fields": {
      "backend_port": {
        "description": "The port that the backend will listen on",
        "destination": {
          "env": "PORT"
        },
        "immutable": true
    },
    "required": [
      "backend_port"
    ]
  }
}
```

This is also not internally consistent with how `immutable` is treated as a property of each parameter.

I propose that we refactor the parameter spec to remove `fields` and make `required` a property of the parameter type, eg:

```json
{
  "parameters": {
    "backend_port": {
      "description": "The port that the backend will listen on",
      "destination": {
        "env": "PORT"
      },
      "immutable": true,
      "required": true
    }
  }
}
```

**Comment by technosophos** [comment]
I believe `"required": [ ... ]` is a result of using JSON Schema's syntax. I don't think we can change that and still be able to say that parameters are defined according to JSON Schema. However, we could change the behavior of `required` in `credentials` to match.

**Comment by jlegrone** [comment]
> I don't think we can change that and still be able to say that parameters are defined according to JSON Schema.

Do we state that `parameters` is a JSON schema document in the spec? I wasn't aware that was a constraint (we currently include non-normative fields like `destination` and `immutable`). A `required` field can still be correctly described in the bundle schema itself (see [credentials](https://github.com/deislabs/cnab-spec/blob/8ec6c23db9bbc404be551ef13872c19fe03cc437/schema/bundle.schema.json#L22-L26)).

See additional comments on tradeoffs [copied from slack](https://cloud-native.slack.com/archives/CEX1W7WMD/p1563197918260200?thread_ts=1563192146.256300&cid=CEX1W7WMD) below:

> I think bundle authors will tend to already have an index of parameters in mind, so keeping things like `required` and `immutable` colocated will help them enforce correctness during editing, PR review, etc. If you have to scroll to see if something has actually been marked required or not, you're less likely to. Also, allowing an explicit `"required": false` in bundle.json is more self-documenting for future readers than omission from the required array.

**Comment by technosophos** [comment]
I agree on the ergonomics. I think `required: []` feels clunky, and is easy to mis-read or ignore. Maybe since our minor reorganization of the JSON Schema stuff it is possible to move it. @ryanmoran might be best to answer that

**Comment by technosophos** [comment]
If anyone else feels  like weighing in.... this is something that would be nice to change before 1.0 if we really want to. On the flip side, I can see the argument for not making a late breaking change.

**Comment by vdice** [comment]
I'd definitely be in support of this.  Indeed, it would be a good to get in pre-1.0 if consensus can be reached quickly and the breaking change doesn't prove too disruptive to others.
