### ISSUE TITLE
Resolve the `immutable` and `readOnly` behavior of parameters

### ISSUE THREAD

**Issue by jeremyrickard** [deislabs/cnab-spec#229]
For more descriptive text, see https://github.com/deislabs/cnab-spec/pull/227#issuecomment-513835322.

TL;DR, `readOnly` in the definition of a param seems to cover what `immutable` on a parameter is intended for. Is it needed as a bespoke functionality? 

Can we remove `immutable` and rely upon the `readOnly` attribute of the definition for now? Or do we need this as a separate thing (i.e. two params share the same definition but one is immutable and one is not?). I think it would be useful to try and figure out if we want to resolve this prior to 1.0 or if it's something we think we can deprecate in the future?

**Comment by technosophos** [comment]
The original discussion on `immutable`: https://github.com/deislabs/cnab-spec/issues/181

/cc @simongdavies

**Comment by jeremyrickard** [comment]
Thanks for linking that @technosophos

**Comment by technosophos** [comment]
I'm leaning toward removing `immutable` for the initial CNAB Core 1.0 release. If we need to add it back after the release, when we've had time to discuss how to keep it from being confusing to the user, we can do that.

**Comment by jeremyrickard** [comment]
I'm good with that too. @ryanmoran what say you?

**Comment by ryanmoran** [comment]
With this reversion, will we be also reverting the change in https://github.com/deislabs/cnab-spec/pull/227?

If not, we should probably also remove the wrapping `fields` object in `outputs` as they are now no longer symmetric.

**Comment by jeremyrickard** [comment]
I don't have a strong opinion on reverting #227 or applying the same pattern to Outputs. I think either is acceptable.
