### ISSUE TITLE
What happens after a failed Install action?

### ISSUE THREAD

**Issue by astrieanna** [deislabs/cnab-spec#237]
In the spec, it is assumed that the install action will be run once, upgrade zero or more times, and uninstall once. What are runtimes expected to do when those invocations fail?

This needs to be clearly defined in the spec so that both runtimes and bundle authors can write correct implementations. A few possible approaches:

# Install
Either of the first two options should be easy to add to the spec because they make consistent choice for how to behave when `install` fails; it's a clarification rather than a real addition. This also makes these options easy for runtimes to implement. It's not obvious to me how hard either option will turn out to be for bundle authors (it depends on how complex their `install`/`upgrade` and `uninstall` actions are).

1) After a failed `install`, the CNAB runtime should reinvoke the `install` action again (on user request; they likely need to fix either an underlying problem with their infra or a parameter they passed in). Bundles must be written such that `install` is ok with being rerun if it failed.

2) ~After a failed `install`, the CNAB runtime must not reinvoke the `install` action again. After users have a chance to fix the underlying problems or parameter errors, the `upgrade` action should be run. Bundles must be written such that `upgrade` can handle cases where `install` failed at the first opportunity.~ Option 1 is just better.

3) An additional form of output is added to the CNAB spec; the goal is to allow the bundle to signal to the runtime. This output allows a bundle to indicate whether it should "count as being installed". If the `install` action got far enough to create resources that need to be deleted later, then it counts as installed and `upgrade` should be run next (and `uninstall` is a valid action). If the `install` action did not do anything (e.g. the first url param it tried to use had a typo), then it does not count as installed, `install` should be run again and `uninstall` is not an action that makes sense to run. This option adds more complexity to the spec in service of likely simplifying some bundle implementations.

4) After a failed install, the CNAB runtime marks the bundle state in error and the only action that can be run successfully against the bundle is uninstall. Bundle authors only handle partial installs in `uninstall`. It is a straight-forward change for the spec and runtimes. This gives users a clear way to clean-up partially created installations, but makes the workflow for retrying failures "install-uninstall-install-uninstall..." rather than "install-install-...".

# Upgrade

1) After a failed upgrade, the CNAB runtime should reinvoke the upgrade action again (on user request; they likely need to fix either an underlying problem with their infra or a parameter they passed in). Bundles must be written such that upgrade is ok with being rerun if it failed.

3) An additional form of output is added to the CNAB spec; the goal is to allow the bundle to signal to the runtime. This output allows a bundle to indicate whether it should "count as being upgraded". If the upgrade action got far enough to edit the real world, then it counts as upgraded and upgrade with the new bundle should be run next. If the upgrade action did not do anything (e.g. the first url param it tried to use had a typo), then it does not count as upgraded, upgrade should be run again and the old bundle should be used for all actions. This option adds more complexity to the spec in service of likely simplifying some bundle implementations.

4) ~After a failed upgrade, the CNAB runtime marks the bundle state in error and the only action that can be run successfully against the bundle is uninstall. Bundle authors only handle partial upgrades in uninstall. It is a straight-forward change for the spec and runtimes. This gives users a clear way to clean-up broken deployments, but~ dead-ends the ability to manage a deployment after you fat-finger one parameter.

# Uninstall
1) After a failed uninstall, the CNAB runtime should reinvoke the uninstall action again (on user request; they likely need to fix either an underlying problem with their infra or a parameter they passed in). Bundles must be written such that uninstall is ok with being rerun if it failed. This failure could have happened on the first line of the uninstall action, so installation is viewed as in a potentially ok state. **`upgrade` and `uninstall` are both ok to run**

1) After a failed uninstall, the CNAB runtime marks the bundle state in error. It should reinvoke the uninstall action again (on user request; they likely need to fix either an underlying problem with their infra or a parameter they passed in). Bundles must be written such that uninstall is ok with being rerun if it failed. Because the action may have deleted most of the installation, do not run actions other than uninstall.
**only `uninstall` is ok to run**

**Comment by glyn** [comment]
Another option was proposed at today's CNAB community call:

4. After a failed `install`, the CNAB runtime marks the bundle state in error and the only action that can be run successfully against the bundle is `uninstall`.

From the bundle author's point of view, I think I'd favour option 1 or option 4.

Option 2 feels a bit strange because the upgrade could have to cope with all kinds of intermediate states in the installed software. Also, I think it's more natural from a runtime user's perspective to repeatedly attempt to install rather than "upgrading" to the same version.

Let's try to cover `upgrade` and `uninstall` failures too. A side note: is it valid to "downgrade" by running `upgrade` using an earlier version of the bundle?

**Comment by astrieanna** [comment]
> 4. After a failed `install`, the CNAB runtime marks the bundle state in error and the only action that can be run successfully against the bundle is `uninstall`.

I will add this to the top, to track the list of options.
 
> Option 2 feels a bit strange because the upgrade could have to cope with all kinds of intermediate states in the installed software. Also, I think it's more natural from a runtime user's perspective to repeatedly attempt to install rather than "upgrading" to the same version.

I agree; I think Option 1 is better than Option 2. I just wanted to give both because they're about as easy for the spec/runtime and I could be missing something. I'll strike Option 2 through to represent that it's just a worse version of Option 1.

> Let's try to cover `upgrade` and `uninstall` failures too.

I'll add a section for these at the top.

>A side note: is it valid to "downgrade" by running `upgrade` using an earlier version of the bundle?

Let's move this to a separate issue; I've created [#246](https://github.com/deislabs/cnab-spec/issues/246#issue-478365406).

**Comment by sbawaska** [comment]
I think we need a combination of `#1` and `#4` above.
As a bundle user, I would expect to run the `install` command until I get the command correct i.e. figure out the missing parameters/required permissions etc. Once all the preconditions are verified, and the install process starts, any subsequent failures should require an `uninstall` operation.

**Comment by ashwin-venkatesh** [comment]
Having a combination of `#1` and `#4` alludes to having a `preinstall` command that runs a bunch of pre-checks to ensure the the infra is in a "good" state for an install. From an end user perspective, I like option `#1` as it has a nice flow of `install`-`install`-`install`, but as an author, the idea of the `install` step not having to make assumptions about what may or may not exist on the target is very appealing.
Option `#1` also looks good in a failed upgrade situations.

On a slight tangent, I wonder if a failed `install/upgrade` should enforce roll backs?

**Comment by chris-crone** [comment]
Option 4 is the safest for install but I agree that specifically when upgrading a way to rerun the command would be nice (i.e.: option 1).

I think that we should punt this to bundle authors with a recommendation to support rerunning at least the upgrade action.
