### ISSUE TITLE
Claims: Gap in spec re: custom?

### ISSUE THREAD

**Issue by vdice** [deislabs/cnab-spec#240]
While working on the [cnab-go ticket](https://github.com/deislabs/cnab-go/issues/74) to update its Claim struct in accordance with the claims spec, I'm noticing the following:

The [claim.schema.json](https://github.com/deislabs/cnab-spec/blob/master/schema/claim.schema.json) file has a [custom](https://github.com/deislabs/cnab-spec/blob/master/schema/claim.schema.json#L44-L46) section as follows:

```
    "custom": {
      "$comment": "reserved for custom extensions"
    },
```

However, there doesn't appear to be a mention of this section in https://github.com/deislabs/cnab-spec/blob/master/400-claims.md.

I can add a section in 400-claims, but first want to confirm that this `custom` section is intended to stay in the claims spec.

If intended to stay, would we add more definition to this section, e.g. `"type": "object"`, etc.?  Or keep wide open and mention it's totally up to the runtime tool to use or ignore as they see fit?

**Comment by jeremyrickard** [comment]
I think we should add it in the 400-claims. This isn't part of the core spec so I think we're free to iterate on that. I _think_ it was an omission. I think it makes sense to include, just like we have it for the bundle itself, extensions might need to store whatever.
