### ISSUE TITLE
Claims: Schema has invalid URI for bundle spec ref

### ISSUE THREAD

**Issue by vdice** [deislabs/cnab-spec#241]
The Claim schema has a [$ref](https://github.com/deislabs/cnab-spec/blob/master/schema/claim.schema.json#L37) field associated with its `bundle` property pointing to a URI that doesn't exist.  (`http://cnab.io/v1/bundle.schema.json`)

We should ensure this URI exists and/or update it accordingly.

I hit this in an attempt to validate a generated claim programmatically; the library used attempted to fetch the ref'd schema but errored out as it was not found.

**Comment by vdice** [comment]
Actually, we might make this issue more general to ensure the base [bundle schema](https://github.com/deislabs/cnab-spec/blob/master/schema/bundle.schema.json)'s `$id` (`http://cnab.io/v1/bundle.schema.json`) represents a valid URI that can be fetched over the network.

**Comment by itowlson** [comment]
Minor note: JSON Schema reference URIs are not expected to be traversable; they are only identifiers, not locators.

"Even though the value of a $ref is a URI, it is not a network locator, only an identifier. This means that the schema doesn’t need to be accessible at that URI, but it may be. It is basically up to the validator implementation how external schema URIs will be handled, but one should not assume the validator will fetch network resources indicated in $ref values."

https://json-schema.org/understanding-json-schema/structuring.html#reuse

So it's up to validators to gather all the schemas they're going to need using out-of-band knowledge, and use the `$id` to link them together.

From a human point of view, though, having the schema available at its `$id` URI sure helps the _author_ of the validator to find the referenced schemas they need!

**Comment by vdice** [comment]
Tracking the work in https://github.com/deislabs/cnab.io/issues/15; closing this ticket.
