### ISSUE TITLE
Clarify the expected behaviour of multiple invocation images

### ISSUE THREAD

**Issue by itowlson** [deislabs/cnab-spec#244]
A bundle may specify multiple invocation images.  When a CNAB runtime executes such a bundle, does it execute a single invocation image, or does it execute all compatible invocation images?  If only a single image, how is this determined?

The current Duffle behaviour appears to be to pick the first invocation image in the JSON array whose image type is compatible with the driver specified by the user, but this is not mandated by the spec as far as I can see.

(If this is the desired/expected behaviour, it makes it pointless to have two images with the same image type, which would be a good thing for a linter/validator to pick up.)

**Comment by glyn** [comment]
I'm not sure matching image type is the whole story. What if there are multi-arch (OCI or docker) invocation images with no matching architecture or OS? We'd presumably skip these too, although I'm not sure what precise mechanism we'd use to do the matching. Would we try executing them and spot a particular kind of failure?
