### ISSUE TITLE
Clarify how outputs are stored in a claim

### ISSUE THREAD

**Issue by itowlson** [deislabs/cnab-spec#245]
The Claims specification says "The output data saves the contents of each output file at the end of the action. The data is a map from output name as defined in the bundle to the content of the file located at the path defined for that output."  (https://github.com/deislabs/cnab-spec/blob/master/400-claims.md#outputs)

* Are output file contents always recorded in the claim `outputs` section as strings, or are they parsed according to their schema?  E.g. if `count` is specified to be of type `integer`, would it be recorded as `"count": 17` or `"count": "17"`?
  * The Claims schema says only that the `outputs` property is of type `object`, which does not help pin down the compliant behaviour.  If outputs are always strings, then let's express that in the schema.

* If an output file contains binary data, whose responsibility is it to encode it so that it can be included in the claim JSON?  That is, is the invocation image required to provide only text files as outputs (and to pre-process binary files into e.g. base64 before returning them)?
  * If so, what text encodings are implementations required to support?

**Comment by vdice** [comment]
For the first bullet point, I'd think we'd want the value to be of the type associated with the corresponding output definition (the valid json schema type).  It appears the spec needs updating to clarify this, if we agree on the aforementioned, unless the spec truly intends to keep it wide open/undefined (expecting/allowing runtimes to decide what type of output values are recorded).

For the second, as I understand it, if an output is designated as `type` string with an associated `contentEncoding` in a bundle.json, the expectation is that the invocationImage will be placing this output in the proper place (`/cnab/app/outputs/myoutput`) with contents encoded according to `contentEncoding`.  When it comes to saving this output's value in the claim, the runtime would  copy these same contents from the invocationImage to the generated `claim.json` file (value of type string, as declared in the bundle.)  So, I believe the onus for encoding is on the invocationImage here.

**Comment by itowlson** [comment]
Another question that came up: When an operation runs does it replace all outputs in the claim or only the ones that have it in their `applyTo`?  E.g. if output `a` applies to actions `install` and `status`, and output `b` applies only to `status`, then after doing an `install` followed by a `status` what would I have in my claim?

**Comment by itowlson** [comment]
@vdice Re the first bullet point, I am okay with that though it was not quite what I expected.  So runtimes are expected to parse (and optionally validate?) the output contents if the type is other than `string`?

Re the second, that sounds fine.  Most bundle authors will not bother to specify a `contentEncoding` but I expect most outputs will be inferred correctly by most tooling languages!  Should we clarify in the spec, and perhaps add a minimum requirement that a runtime must handle some minimal encoding such as UTF-8?

**Comment by radu-matei** [comment]
@itowlson - has this been answered? Can we close this issue?
Thanks!

**Comment by glyn** [comment]
Consensus at CNAB meeting: let's close this. Please re-open if it needs to be looked at in the claims spec.
