### ISSUE TITLE
Can you "downgrade" deployed software by running the `upgrade` action?

### ISSUE THREAD

**Issue by astrieanna** [deislabs/cnab-spec#246]
Is it valid to "downgrade" by running `upgrade` using an earlier version of the bundle?

This impacts what CNAB runtimes should allow and also how bundle authors should write their bundles.

The runtime does not provide the "to" and "from" `bundle.json`s to the invocation image on upgrade, so the bundle only has the parameters or the running software as a source of "which version deployed this".

**Comment by chris-crone** [comment]
As the logic for what happens during an upgrade lives in the invocation image, I'd recommend letting the bundle authors decide.
