### ISSUE TITLE
How should runtimes handle `default` in definitions?

### ISSUE THREAD

**Issue by itowlson** [deislabs/cnab-spec#249]
1. If I have a parameter which is `required: true` and a definition which specifies a default value, does the default value inherently satisfy the requirement that the parameter be set?  Or must the user still always specify the parameter value (e.g. via `duffle --set`)?

2. If a parameter with a default is omitted, is the runtime meant to inject the default value when it runs the invocation image, or does it set an empty value and it's up to the invocation image to use a default (hopefully one which is consistent with the schema default)?

3. Is it correct to say that `default` is always ignored on output definitions because the invocation image is required to provide a value for every output?

**Comment by youreddy** [comment]
1. the default value should inherently satisfy the requirement
2. feels like it would be easier for the runtime to inject it
3. from what I'm reading [here](https://github.com/deislabs/cnab-spec/blob/master/101-bundle-json.md#outputs), `outputs` does not have a `default` field.

If there's no disagreements on the above, we should make these clarifications to the spec.

**Comment by carolynvs** [comment]
For 3, an output references a definition, just as a property does. The schema for definition is shared between output and property so an output can reference a definition which could have a default defined.

Based on that, it's a valid question to ask if the runtime should default an output when the invocation image doesn't write to the output file (right now it's a hard error in cnab-go about the file not being written). IMO, I don't see a problem with saying "If the invocation didn't write to the file, default the output to this value". It could be helpful in some cases.
