### ISSUE TITLE
Spec does not specify how to stringise non-scalar parameter types

### ISSUE THREAD

**Issue by itowlson** [deislabs/cnab-spec#250]
The spec allows parameters to be of type `object` and `array`.  But the runtime has to inject these parameter values into the invocation image via environment variables or files, which are inherently stringular.  There is no issue here for numbers, strings and booleans which have widely agreed`*` string representations; but we should state how runtimes should stringise object and array values, e.g. as JSON literals.

`*` Though not necessarily as widely agreed as you would like, e.g. a naive JavaScript implementation might easily inject numbers in scientific notation which, say, an invocation image binary written in Go might not readily parse.

**Comment by astrieanna** [comment]
Kind of related, PR to fix Duffle injecting `object` and `array` as golang prints them: https://github.com/deislabs/cnab-go/pull/96

**Comment by carolynvs** [comment]
Based on how the PR was resolved, do we need to update the spec to match what we did in cnab-go?

**Comment by carolynvs** [comment]
Radu says that we don't have to worry about numbers because canonical json doesn't allow for anything but integers. 😀

**Comment by carolynvs** [comment]
I'll update the spec to clarify that objects and arrays must be represented as json.
