### ISSUE TITLE
Clarify stateless actions and installation names

### ISSUE THREAD

**Issue by itowlson** [deislabs/cnab-spec#252]
The spec at https://github.com/deislabs/cnab-spec/blob/master/101-bundle-json.md#custom-actions says: "Stateless actions can be invoked on a non-existing installation."

What is the intent of this?

1. It is legal to perform a stateless action with an installation name that does not correspond to any installation, or without an installation.

2. It is legal to perform a stateless action without an installation (but if you do give a name then it has to exist).

**Comment by silvin-lubecki** [comment]
On our side, `docker app` generates CNAB bundles with 2 stateless actions:
- one is `inspect`: it pretty prints the content of the bundle, so it does not require any installation
- the other is `render`: it prints a compose file filled with dynamic parameters, and does not require any installation either.

Hope it will give you some context @itowlson 👍

**Comment by astrieanna** [comment]
> The action does not act on a claim, and does not require credentials.

Not allowing stateless actions to require credentials seems limiting. What if you wanted to run a `preflight-checks` action that would, for example, check that a Kubernetes cluster meets all your requirements to install on it?
You could, of course, leave those checks in `install` and have the `install` action fail if any of those checks failed, but if a bundle wanted to provide that user experience, they would not be able to have the runtime do the standard "did you give the required credentials" checks & feedback.
