### ISSUE TITLE
What does 'this' refer to?

### ISSUE THREAD

**Issue by duglin** [deislabs/cnab-spec#37]
in 100-CNAB, there's this line:
```
Finally, this document describes a format for invocation images...
```
Does "this document" refer to the current md file (100-CNAB) or does it mean the bundle? I'm guessing it should be "Finally, the bundle describes...." but I'm not 100% sure so I didn't open a PR

**Comment by technosophos** [comment]
Over time, the offending phrase was rewritten independently of this issue. So I am marking the issue closed.
