### ISSUE TITLE
102-invocation-image.md questions/comments

### ISSUE THREAD

**Issue by duglin** [deislabs/cnab-spec#42]
> The material necessary for reproducing the invocation image (Dockerfile and packer.json are two examples)

Do you expect this to also be provided for the other images as well?  Do you expect the actual Dockerfile to be there or just a pointer to where it lives - like a URL to it in a github repo? I would expect some consistence here between all of the images.

Including the Dockerfile is an interesting choice... how much other info do you expect people to include to be able to fully rebuild the image? In many cases I would suspect that a Dockerfile is not sufficient so are you expecting them to recreate their entire build env in here? My gut is telling me to leave this out for now and add it later because this feels like it might be a rat-hole w/o clear boundaries. In the interest of not asking people to duplicate info, I'd suggest just a pointer to whatever info is needed to recreate it - if even that.

> `cnab/ `

re: `/`  -  Do we assume non-windows file-system?  :-)  On the serious side, I haven't seen any mention of the platform in which this stuff will run, are you assuming Linux or Windows? Assuming multi-arch images? If a Linux dev built a cnab bundle, do you expect a Windows person to be able to `cnab install` it? Some discussion of how you see the differences between various OSs, architectures, etc... might be good.  Should also talk about what the prereqs are for running the `cnab` tool.

Is the cnab bundle a zip file or tar ball? 

> This directory MUST have a subdirectory named app.

Why? Why not just put `run` at the root of the `cnab` dir? Even if you expect other top-level things, it sounds like `run` is always the main entry point for everything so why bury it under `app` ? Or put it another way, what value does the `app` dir provide for this executable? What would break, or be ambiguous, if it wasn't there?

> This directory MUST NOT have any files or directories not explicitly named in the present document. 

be careful. A v1.0 processor that sees v1.1 (optional) file, might halt process and error out based on this text. I think you'll find it easier to just say that unknown/extension files can be ignored then a v1.0 processor can still process a v1.1 bundle. If you're afraid of name conflicts then tell people to prefix their extension files with some domain (eg company) specific word - but they're added them at their own risk.  If you want some gory info on a related topic see: https://github.com/cloudevents/spec/pull/353/files#diff-ed0940ecbc7be65c47b9414d516b3490R180

> The OPTIONAL /cnab/build Directory

I'd add this dir to "The File System Layout" section FS map thingy.

> However, the intention is to provide space for artifacts that are used during the assembly (or re-assembly) of the bundle, but are not part of the execution of a bundle action

This feels similar to asking for source code to live in a resulting docker image even though its not used at runtime. To save space, I doubt people will want their bundle (or images) to include anything but the bare minimum, so I'd keep the artifacts needed to build the images out of the images themselves.

> Base Bundles

Should this be "Base Invocation Images"? Are we inheriting CNAB bundles or just invocation images? The body of the section focuses on images.

> The most frequent way in which is occurs is...

s/which is/which this/

**Comment by joenoon** [comment]
> re: / - Do we assume non-windows file-system? :-) On the serious side, I haven't seen any mention of the platform in which this stuff will run, are you assuming Linux or Windows? Assuming multi-arch images? If a Linux dev built a cnab bundle, do you expect a Windows person to be able to cnab install it? Some discussion of how you see the differences between various OSs, architectures, etc... might be good. Should also talk about what the prereqs are for running the cnab tool.

I'm curious about this as well.  We currently develop an application consisting of multiple containers.  This is great for many scenarios - on-prem with some IT, private/public cloud, generally any scenario where the word linux doesn't cause a blank stare.  But where we currently don't have a good plan is for the low-tech Windows user who we'd like to be able to "install" our app.

Reading through this I got the hope that the goal of this project may be to allow for a scenario like this, where any user on any platform would be able to "cnab install" our application without worrying about the details of the underlying docker/etc tech.  Does anyone know if this is the case?

**Comment by technosophos** [comment]
I believe that all of these issues are now resolved.
