### ISSUE TITLE
conflicting parameter names

### ISSUE THREAD

**Issue by itaysk** [deislabs/cnab-spec#56]
Spec should address the case of conflicting parameter names, for example the image already has a similar env var at runtime. This is a rare edge case but better to define the behaviour in the spec rather than to leave for implementors to decide (or worse, to not decide).

**Comment by itaysk** [comment]
it's not what I meant but reading this again after a while it seem over specification so I'll close this

**Comment by technosophos** [comment]
Sorry for the misunderstanding.
