### ISSUE TITLE
image substitution

### ISSUE THREAD

**Issue by itaysk** [deislabs/cnab-spec#58]
Images used by the application are referenced in the bundle and substituted by the runtime. At first I thought about substitution scenarios which are not defined in the spec like case sensitivity, substrings, wildcards, and more.. But then it occurred to me that it's better to just use regexp substitution, possibly with the familiar `sed` format. For simple uses it won't impose too much burden on the user, but it will enable advanced uses with ease.

**Comment by itaysk** [comment]
also addresses https://github.com/deislabs/cnab-spec/blame/master/101-bundle-json.md#L269

**Comment by simonferquel** [comment]
For some scenarios, declarative substitutions might not be enough (e.g.: replacements inside heavily templated files that are not valid yaml/json/toml, or replacements in compiled code data structures). For this, I suggest that complementary to the declarative approach, we also inject a map of `component name -> image name` in a well known location of the invocation image at run time. PR https://github.com/deislabs/duffle/pull/605 on duffle implement the idea, and a correlated PR in docker-app leverages that as well.

**Comment by technosophos** [comment]
I think this one is now resolved by #62
