### ISSUE TITLE
Real world use cases for thick bundles?

### ISSUE THREAD

**Issue by afkham** [deislabs/cnab-spec#64]
I am trying to understand where thick bundles will be useful. I have gone through the ycombinator thread as well as the spec, but it is not clear why anyone would really need this. Can someone provide some concrete examples. Thanks.

**Comment by garethr** [comment]
In my view I think there are a two main use cases for the thick bundles:

1. *A single signed artefact* - it's useful in some security-conscious environments to have a single artefact, without any dependencies, which can be individually reasoned about, have metadata associated with it, can be cryptographically signed, etc. 
2. *Offline installation* - either as a subset of the security conscious usecase above, or for offline environments (some edge setups, firewalled environments without internet or internal network connectivity). This is the "install from a USB drive" usecase.

**Comment by technosophos** [comment]
Our main use case is air gap networks like a SCIF. The idea is that you export a signed artifact to some physical media, and then move it across a physical boundary. But when you reconstitute the bundle on the "far side", you can still assert the integrity of the entire application.

It's also convenient for long-term storage.

**Comment by GreenCee** [comment]
Adding a use case from regulated industries and extending the reach of cloud native application models.
Network segmentation

For PCI-DSS scope minimzation, wrapping things into a thick bundle then only sending it through inside the boundary can avoid inadvertantly including your entire CI/CD in scope. Similar for segmented networks to deliver verified artifacts only.

Futures I see are the use of bringing cloud local, whether it be a solution like Azure Stack or AWS Outposts, or a server providing the same subset of cloud APIs. These pop up today in energy industry commonly, but Chick-fil-A's use of Kubernetes is likely to become common. 
The thick bundle shines where local processing is needed for the restaurant, but they would no longer need business class internet only relying on wireless for transactions.

**Comment by technosophos** [comment]
Ah, yes -- that is a great example of a use case.

**Comment by technosophos** [comment]
I believe this one may now be marked "resolved"
