### ISSUE TITLE
Potential for clash in environment vars with credentials

### ISSUE THREAD

**Issue by garethr** [deislabs/cnab-spec#69]
Consider the following

```json
{
    "name": "notrelevant",
    "version": "0.1.0",
    "invocationImages": [
        {
            "image": "notrelevant"
        }
    ],
    "parameters": {
        "something": {
            "type": "string",
            "destination": {
                "env": "SOMETHING"
            }
        }
    },
    "credentials": {
        "something": {
            "env": "SOMETHING"
        }
    }
}
```

Note both the parameter and credential attempting to put a value in the same ENV. I think this should be invalid. It's not possible to pass both values as the same environment variable, but it's easy enough in the client to fail early. 

I don't think I saw mention of this in the spec, and I think the behaviour should be specified rather than left to clients.  Opening this for discussion to double check I've not missed something and the above reasoning is valid. Happy to submit a PR against the spec if so.

**Comment by radu-matei** [comment]
And I don't think this is restricted to environment variables either - clashing file paths between credentials and parameters can exists as well in this case, right?

**Comment by garethr** [comment]
Ah, yes. I just haven't got round to implementing file path params yet so hadn't though about that.

I think I'm of the same mind, duplicate paths should be invalid.
