### ISSUE TITLE
Should claims really be part of the spec ?

### ISSUE THREAD

**Issue by simonferquel** [deislabs/cnab-spec#84]
It is more a question than a suggestion.

IMO, claims seem more to be an implementation detail of Duffle. It can be used as a simple way to describe how a CNAB implementation can keep track of existing installations, as well as what data must be stored for future invocations as part of the runtime specification.

**Comment by radu-matei** [comment]
I think it becomes a question of interoperability between tools, and the same question can be: _Do I want to be able to use tool A to install a bundle and tool B to uninstall it?_

**Comment by technosophos** [comment]
At this point, we are breaking the spec down into multiple specifications:

- 100 CNAB Core: Just the stuff about the CNAB format itself
- 200 CNAB Regsitry: Just the stuff describing how CNABs are to be stored in OCI registries
- 300 CNAB Security: The part about signing, verifying, and attesting with TUF and InToto

We could add:

- 400 CNAB Claims

Thoughts?
