### ISSUE TITLE
URI field in image

### ISSUE THREAD

**Issue by radu-matei** [deislabs/cnab-spec#89]
In some examples there is a `uri` field on `image` that appears (see examples in [101-bundle-json.md](https://github.com/deislabs/cnab-spec/blob/master/101-bundle-json.md#the-bundlejson-file) and [105-signing.md](https://github.com/deislabs/cnab-spec/blob/master/105-signing.md#digesting-objects-in-the-bundlejson):

```
   "images": [
        {
            "name": "image1",
            "digest": "sha256:aaaa624b58dbbcd3c0dd82b4c53f04194d1247c6eebdaab7c610cf7d66709b3b",
            "uri": "urn:image1uri",
            "refs": [
                {
                    "path": "image1path",
                    "field": "image.1.field"
                }
            ],
        }
    ]
```

However, this field appears neither in the spec, nor in the JSON schema.
Should it be removed from the examples, or added in the spec and schema?

**Comment by bacongobbler** [comment]
Yeah it should be replaced with `image`. Also discussed in another thread here: https://github.com/deislabs/cnab-spec/issues/66#issuecomment-457472759
