### ISSUE TITLE
Discrepancy between spec and schema for schemaVersion

### ISSUE THREAD

**Issue by garethr** [deislabs/cnab-spec#92]
The spec [says](https://github.com/deislabs/cnab-spec/blob/master/101-bundle-json.md):

> The schema version of the bundle, as a string with a v prefix. This schema is to be referenced as v1 or v1.0.0-WD

The the examples in the spec show:

```json
"schemaVersion": "v1",
```

However, the [JSON Schema](https://github.com/deislabs/cnab-spec/blob/master/schema/bundle.schema.json#L9) states:

```json
 "description": "The version of the CNAB specification. This should always be the integer 1 for this schema version.",
```

I think the latter is wrong in this case, but which do we prefer?

**Comment by simongdavies** [comment]
Why does the spec need a schemaVersion property? Shouldn't it just have a $schema property that points to the spec version?

**Comment by technosophos** [comment]
@simongdavies That is a good question. I need to read up on that.

**Comment by technosophos** [comment]
Here's the relevant (but not very informative) portion of the spec: https://json-schema.org/latest/json-schema-core.html#rfc.section.7

The formats I am seeing look like this:

```
"$schema": "http://json-schema.org/draft-07/schema#",
```
So we could do `"$schema": "https://cnab.io/1.0.0-WD/schema.json"` and follow approximately the same naming scheme.

**Comment by simongdavies** [comment]
Correct - this will make tools that understand JSON schema work as well, for example if I set the property to    "https://raw.githubusercontent.com/deislabs/cnab-spec/master/schema/bundle.schema.json"
 in an existing bundle.json that has not been updated with recent changes and then open it in VS Code I see warnings:

<img width="852" alt="image" src="https://user-images.githubusercontent.com/1397489/52710501-639f8580-2f87-11e9-8daf-e6f5ef12f411.png">

**Comment by technosophos** [comment]
I've been gathering feedback on whether to use `$schema`, and opinions are really all over the map. So far, the best case I've heard is this:

> `$schema` should point to a specific file, and is not considered "human parseable", while a `schemaVersion` field should be kept, and should be human readable data.

In absence of a firm resolution, I'm leaving this open for now.

**Comment by simongdavies** [comment]
My initial thoughts were that if the value of the $schema property is a unique Uri then the addition of an additional property to indicate the version of the schema was unnecessary as the version would be encoded in the schema Uri, however , requiring both seems like a reasonable compromise. 

Its probably important to ensure that:

1.  As changes are applied to the spec that those changes are always reflected in the schema 

1. That a schema is released each time the schemaVersion changes.

**Comment by technosophos** [comment]
Okay, I fixed the version number in the JSON schema, and I think when we do the release of CNAB Core 1.0, we can add in the `$schema` URL for hte final 1.0 version.
