### ISSUE TITLE
Change to images from list to map not updated in schema

### ISSUE THREAD

**Issue by garethr** [deislabs/cnab-spec#93]
When https://github.com/deislabs/cnab-spec/pull/62 was merged the changes weren't made to the schema, which still shows the image list: https://github.com/deislabs/cnab-spec/blob/master/schema/bundle.schema.json#L68

cc. @simonferquel @technosophos

**Comment by radu-matei** [comment]
See https://github.com/deislabs/cnab-spec/pull/81/files ?

**Comment by garethr** [comment]
Yup, duplicate. Thanks.
