### ISSUE TITLE
Missing required status for informational metadata for bundles

### ISSUE THREAD

**Issue by radu-matei** [deislabs/cnab-spec#96]
[As they are currently defined](https://github.com/deislabs/cnab-spec/blob/master/101-bundle-json.md#informational-metadata), the bundle informational metadata does not specify a required status.

This issue keeps track of adding that status.

**Comment by simonferquel** [comment]
I would also like to standardize a `status-json` custom action that if implemented, should return a json payload via stdout respecting a well known schema so that we can present status results in a web-ui

**Comment by garethr** [comment]
@simonferquel I'd say that's a separate question that warrants a separate issue,

I think the schema is probably correct in my view here. https://github.com/deislabs/cnab-spec/blob/master/schema/bundle.schema.json#L105

ie. of those fields, `name` is required, while `description` and `maintainers` are optional.

**Comment by technosophos** [comment]
@radu-matei what would the values of `status` be?

**Comment by radu-matei** [comment]
I agree with @garethr, I think it should be the same as in the schema.

But @itowlson pointed this out from the same doc: _In descriptions below, fields marked REQUIRED MUST be present in any conformant bundle descriptor, while fields not thusly marked are considered optional._

I completely missed this, and while I think we could add the status, to be consistent with the rest of the spec where it's specified, we don't actually have to.

**Comment by technosophos** [comment]
OH! I completely misread this and thought you were asking for a required field called `status` on the metadata. 🤦‍♂️
