### ISSUE TITLE
Ambiguous parameter destination required status

### ISSUE THREAD

**Issue by radu-matei** [deislabs/cnab-spec#97]
In [the current form of the spec](https://github.com/deislabs/cnab-spec/blob/master/101-bundle-json.md#parameters), it is unclear whether the parameter destination MUST set both environment variable and path - from the spec:

```
- destination: Indicates where (in the invocation image) the parameter is to be written (REQUIRED)

    - env: The name of an environment variable
    - path: The fully qualified path to a file that will be created
```

Should there be at least a clarification, stating that at least one of  `env` and `path` must be set?

**Comment by garethr** [comment]
Related https://github.com/deislabs/cnab-spec/issues/100

The spec describes the resolution rules for when neither is set.

**Comment by radu-matei** [comment]
Closing in favor of #100.
